### ISSUE TITLE
Document how to update codebase when API spec has been updated

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-date-annotator-example#15]
Add this documentation to the project README. A section for this doc has already been created.

**Comment by gkowalski** [comment]
done

**Comment by tschaffter** [comment]
@gkowalski The documentation should be placed [here](https://github.com/Sage-Bionetworks/nlp-sandbox-date-annotator-example#update-the-codebase-when-a-new-openapi-spec-is-available). Can you please move it there?

**Comment by tschaffter** [comment]
@gkowalski I see the PR. Thanks!
