### ISSUE TITLE
Identify if the local openapi.yaml be customized by developers

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-date-annotator-example#17]
Or is this file overwritten when updating the codebase when a new version of the OpenAPI spec is available?

If we decide that the developer can customize the local openapi.yaml file, document this in the README

**Comment by gkowalski** [comment]
I assumed that if a developer wanted to suggest a change to the openapi.yaml file they would issue a pull request to https://github.com/Sage-Bionetworks/nlp-sandbox-schemas and if accepted would be migrated to this repo buy us.

**Comment by tschaffter** [comment]
@gkowalski Yes, we are responsible for updating this example if the API changes.

**Comment by tschaffter** [comment]
@gkowalski Wait, this ticket is about something else. We need to identify if we want to invite developer to customize their [local copy of the openapi spec](https://github.com/Sage-Bionetworks/nlp-sandbox-date-annotator-example/blob/develop/server/openapi_server/openapi/openapi.yaml). What we want to avoid is a protocol where they customize their local copy of the spec and this copy get overwritten when they update their implementation using `openapi-generator`. Do you know if this is the case?

**Comment by tschaffter** [comment]
## Conclusion

It's OK for developer to customize their local *openapi.yaml* as long as the specification is respected. Also they can conserve their customization after updating the spec by doing a manual review/merge.
