### ISSUE TITLE
The request body for /dates has more keys than we receive from the data node server

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/nlp-sandbox-date-annotator-example#25]
@tschaffter: It appears that the request body is:

```
[
  {
    "createdAt": "2020-10-20T03:19:51.087Z",
    "createdBy": {
      "email": "john.smith@example.com",
      "firstName": "John",
      "lastName": "Smith",
      "username": "John78"
    },
    "id": 0,
    "updatedAt": "2020-10-20T03:19:51.087Z",
    "updatedBy": {
      "email": "john.smith@example.com",
      "firstName": "John",
      "lastName": "Smith",
      "username": "John78"
    },
    "text": "On 09-03-1999, Ms Chloe Price met with Dr Joe.",
    "type": "pathology"
  }
]
```

Unfortunately, we only currently receive the below from the data notes server:

```
{"id": ....
"text":....}
```

This does indeed work, but was just wondering as to why there were these other fields.  It seems like the only fields that are required to use this API is the `id` and `text`.  Do i compare the `dates` with the date results I get form querying the date endpoint in the data node API?

**Comment by tschaffter** [comment]
This ticket is deprecated: the schema of the input object (Note) has been updated since.
