### ISSUE TITLE
Identify format of the logs so they can be interpreted by ELK

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-date-annotator-example#38]
@thomasyu888 The format of the NLP Tool is almost "Gold" and I'll present it on Tuesday during our technical meeting. One of the last elements that we need to figure out is the format of the logs printed to stdout and stderr so we can easily interpret them in our ELK stack. Did you come across a standard or best practices regarding this? I guess that the logs should be prefixed with at least the following information for which we need to define the format:

- timestamp
- message type (e.g. info, warning, error)

**Comment by thomasyu888** [comment]
The logs don't need to be prefaced with time, because ELK timestamps each message.  All people really need to do is create `stdout` from their tool and ELK will capture any of the docker logs.

**Comment by tschaffter** [comment]
What about errors? Shall `stderr` be redirected to `stdout`?

**Comment by tschaffter** [comment]
Will reopen if needed when testing the pipeline and when centralizing logs using ELK.
